# Configuração do Banco de Dados
host: "example.mysql.database.azure.com"  # Endereço do servidor MySQL
port: 3306                                # Porta do servidor MySQL
database: "example_db"                    # Nome do banco de dados
username: "example_user"                  # Nome de usuário para autenticação
password: "example_password"              # Senha do usuário

# Caminho para o arquivo do certificado SSL, caso contrario deixe vazio ""
dbCertFile: "/path/to/your/azure.cer"

# Tamanho mínimo em GB de fragmentação que uma tabela deve ter para ser considerada para otimização.
# Se a fragmentação de uma tabela exceder este valor, a tabela será selecionada para a rotina de otimização.
optimizationFragmentationThreshold: 10
